def inverse(x):
    if not x:
        throw new Exception('Division by zero.')
    return 1/x

try:
    echo(inverse(5), "\n")
    echo(inverse(0), "\n")
catch (e:Exception):
    echo('Caught exception: ',  e.getMessage(), "\n")

try:
    echo(inverse(0), "\n")
catch (e:Exception):
    echo('Caught exception: ',  e.getMessage(), "\n")
finally:
    echo("Second finally.\n")

# Continue execution
echo("Hello World\n")


class MyException extends Exception:
	pass

class Test:
    public testing():
        try:
            try:
                throw new MyException('foo!')
            catch (e:MyException):
                # rethrow it
                throw e
        catch (e:Exception):
            var_dump(e.getMessage())

foo = new Test()
foo.testing()

